title: A Noob's Blog
author: hasmukh96
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  On this blog I talk about my journey to learn coding.

# social links
twitter_username: thesmilingface9
github_username:  hasmukh96

show_excerpts: true # set to false to remove excerpts on the homepage
